# Generated by Django 4.1 on 2022-08-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='due_to',
            field=models.DateField(),
        ),
    ]
