# Generated by Django 4.1 on 2022-08-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_alter_emailmessage_due_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
