# Generated by Django 4.1 on 2022-08-18 15:18

from django.db import migrations, models
import mailing.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_emailmessage_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='due_to',
            field=models.DateField(validators=[mailing.validators.in_the_future]),
        ),
    ]
