# Generated by Django 4.1 on 2022-08-31 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_alter_emailmessage_due_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='due_to',
            field=models.DateField(),
        ),
    ]
